baseURL = "https://morishitamasahide.github.io"
publishDir = "docs"
languageCode = "ja-jp"
title = "Morishita Masahide's blog"
theme = "github-style"
googleAnalytics = ""
pygmentsCodeFences = true
pygmentsUseClasses = true

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  author = "Morishita Masahide"
  description = "For the people"
  github = "morishitamasahide"
  facebook = "morishitamasahide"
  twitter = "morishitamasahide"
  linkedin = "morishitamasahide"
  instagram = "morishitamasahide"
  email = "morishitamasahide"
  url = "https://google.com"
  keywords = "blog"
  lastmod = true
  userStatusEmoji = "😆"
  favicon = "/images/avatar.png" 
  location = "Japan"
  enableGitalk = false
  [[params.links]]
    title = "Link"
    href = "hoge"
  [[params.links]]
    title = "Link2"
    href = "hoge2"
    icon = "/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]